name: hydrate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  android_alarm_manager_plus: ^2.0.4
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.0.5
  dog: ^1.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  http: ^0.13.4
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  shared_preferences: ^2.0.13
  workmanager: ^0.4.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
